### ISSUE TITLE
MissingMethodException isStartOnPluginLoad() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by aarabyan** [mckenfra/gsp-resources#7]
Plugin version - 0.4.2
Grails version - 2.2.4

I gave 'utils' plugin that use gspResources plugin.
And 'utils' plugin is used in application.
I can not start (grails run-app) grails application because  of error in plugin, but building war is OK. (grails war)

Previously it was working, but after some change (that i can not identify ) app fails to start.

| Error 2013-09-16 12:20:54,062 [localhost-startStop-1] ERROR plugins.DefaultGrailsPluginManager  - Error configuring dynamic methods for plugin [gspResources:0.4.2]: groovy.lang.MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginLoad() is applicable for argument types: () values: []
Message: groovy.lang.MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginLoad() is applicable for argument types: () values: []
    Line | Method
->>  334 | innerRun  in java.util.concurrent.FutureTask$Sync

---

|    166 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . in java.lang.Thread

Caused by MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginLoad() is applicable for argument types: () values: []
->>   59 | doCall    in GspResourcesGrailsPlugin$_closure2

---

|    334 | innerRun  in java.util.concurrent.FutureTask$Sync
|    166 | run . . . in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread
2013-09-16 12:20:54,135 [localhost-startStop-1] INFO  resource.ResourceProcessor  - Performing a full reload
| Error 2013-09-16 12:20:55,983 [localhost-startStop-1] ERROR resource.ResourceProcessor  - Unable to load resources
Message: Error creating bean with name 'org.grails.plugin.gspresources.GspResourceMapper': Cannot resolve reference to bean 'org.grails.plugin.gspresources.GspResourceMapperInstance' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grails.plugin.gspresources.GspResourceMapperInstance': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.grails.plugin.resource.ResourceProcessor' to required type 'org.grails.plugin.gspresources.GspResourceProcessor' for property 'grailsResourceProcessor'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.grails.plugin.resource.ResourceProcessor] to required type [org.grails.plugin.gspresources.GspResourceProcessor] for property 'grailsResourceProcessor': no matching editors or conversion strategy found
    Line | Method
->>  593 | createApplicationContext in grails.spring.BeanBuilder

---

|     43 | createResourceMappers    in org.grails.plugin.resource.mapper.ResourceMappersFactory
|   1005 | loadMappers . . . . . .  in org.grails.plugin.resource.ResourceProcessor
|   1074 | reloadAll                in     ''
|    172 | doCall . . . . . . . . . in ResourcesGrailsPlugin$_closure3
|    334 | innerRun                 in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                      in java.lang.Thread

Caused by BeanCreationException: Error creating bean with name 'org.grails.plugin.gspresources.GspResourceMapperInstance': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.grails.plugin.resource.ResourceProcessor' to required type 'org.grails.plugin.gspresources.GspResourceProcessor' for property 'grailsResourceProcessor'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.grails.plugin.resource.ResourceProcessor] to required type [org.grails.plugin.gspresources.GspResourceProcessor] for property 'grailsResourceProcessor': no matching editors or conversion strategy found
->>  593 | createApplicationContext in grails.spring.BeanBuilder

---

|     43 | createResourceMappers    in org.grails.plugin.resource.mapper.ResourceMappersFactory
|   1005 | loadMappers . . . . . .  in org.grails.plugin.resource.ResourceProcessor
|   1074 | reloadAll                in     ''
|    172 | doCall . . . . . . . . . in ResourcesGrailsPlugin$_closure3
|    334 | innerRun                 in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                      in java.lang.Thread

Caused by ConversionNotSupportedException: Failed to convert property value of type 'org.grails.plugin.resource.ResourceProcessor' to required type 'org.grails.plugin.gspresources.GspResourceProcessor' for property 'grailsResourceProcessor'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.grails.plugin.resource.ResourceProcessor] to required type [org.grails.plugin.gspresources.GspResourceProcessor] for property 'grailsResourceProcessor': no matching editors or conversion strategy found
->>  593 | createApplicationContext in grails.spring.BeanBuilder

---

|     43 | createResourceMappers    in org.grails.plugin.resource.mapper.ResourceMappersFactory
|   1005 | loadMappers . . . . . .  in org.grails.plugin.resource.ResourceProcessor
|   1074 | reloadAll                in     ''
|    172 | doCall . . . . . . . . . in ResourcesGrailsPlugin$_closure3
|    334 | innerRun                 in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                      in java.lang.Thread

Caused by IllegalStateException: Cannot convert value of type [org.grails.plugin.resource.ResourceProcessor] to required type [org.grails.plugin.gspresources.GspResourceProcessor] for property 'grailsResourceProcessor': no matching editors or conversion strategy found
->>  593 | createApplicationContext in grails.spring.BeanBuilder

---

|     43 | createResourceMappers    in org.grails.plugin.resource.mapper.ResourceMappersFactory
|   1005 | loadMappers . . . . . .  in org.grails.plugin.resource.ResourceProcessor
|   1074 | reloadAll                in     ''
|    172 | doCall . . . . . . . . . in ResourcesGrailsPlugin$_closure3
|    334 | innerRun                 in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                      in java.lang.Thread
2013-09-16 12:21:03,785 [localhost-startStop-1] WARN  util.GrailsUtil  - [DEPRECATED] Method ConfigurationHolder.getConfig() is deprecated and will be removed in a future version of Grails.
2013-09-16 12:21:03,800 [localhost-startStop-1] WARN  util.GrailsUtil  - [DEPRECATED] Method ApplicationHolder.getApplication() is deprecated and will be removed in a future version of Grails.
2013-09-16 12:21:03,815 [localhost-startStop-1] WARN  util.GrailsUtil  - [DEPRECATED] Method ApplicationHolder.getApplication() is deprecated and will be removed in a future version of Grails.
2013-09-16 12:21:03,820 [localhost-startStop-1] WARN  util.GrailsUtil  - [DEPRECATED] Method ConfigurationHolder.getConfig() is deprecated and will be removed in a future version of Grails.
2013-09-16 12:21:03,821 [localhost-startStop-1] INFO  CacheHeadersGrailsPlugin  - Caching enabled in Config: true
2013-09-16 12:21:07,547 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
| Error 2013-09-16 12:21:07,665 [localhost-startStop-1] ERROR context.GrailsContextLoader  - Error initializing the application: groovy.lang.MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginBootstrap() is applicable for argument types: () values: []
Message: groovy.lang.MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginBootstrap() is applicable for argument types: () values: []
    Line | Method
->>  308 | evaluateEnvironmentSpecificBlock in grails.util.Environment

---

|    301 | executeForEnvironment            in     ''
|    277 | executeForCurrentEnvironment . . in     ''
|    334 | innerRun                         in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                              in java.lang.Thread

Caused by MissingMethodException: No signature of method: org.grails.plugin.resource.ResourceProcessor.isStartOnPluginBootstrap() is applicable for argument types: () values: []
->>   12 | doCall                           in GspResourcesBootStrap$_closure1

---

|    308 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    301 | executeForEnvironment . . . . .  in     ''
|    277 | executeForCurrentEnvironment     in     ''
|    334 | innerRun . . . . . . . . . . . . in java.util.concurrent.FutureTask$Sync
|    166 | run                              in java.util.concurrent.FutureTask
|   1145 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . . . . . . . . .  in java.lang.Thread
2013-09-16 12:21:07,786 [UaalClientService STOPPING] INFO  service.UaalClientService  - Stoping UAAL Client Service
2013-09-16 12:21:07,786 [UaalClientService STOPPING] INFO  service.UaalClientService  - Service was stopped, tasks never started: []
2013-09-16 12:21:07,797 [Thread-9] INFO  impl.SessionFactoryImpl  - closing
2013-09-16 12:21:07,817 [Thread-9] INFO  impl.SessionFactoryImpl  - closing

**Comment by aarabyan** [comment]
It look like 
    def loadAfter = ['resources'] 
solving the problem.

class GspResourcesGrailsPlugin {
    def version = "0.4.2"
    def grailsVersion = "2.0.0 > *"
    def loadAfter = ['resources']

**Comment by mckenfra** [comment]
Thanks very much for raising this issue, and also finding the solution! I'll add the `loadAfter` as you suggest, and upload a new version to the grails central repo.
Cheers,
Francis

**Comment by mckenfra** [comment]
I released version 0.4.3 with the fix - has this fixed your problem?
Cheers,
Francis

**Comment by aarabyan** [comment]
Thanks Francis. 
It is fixed.
Closing issue.

**Comment by mckenfra** [comment]
Great, thanks!
