### ISSUE TITLE
Fatal Error : Trying to access private constant field [org.grails.plugin.resource.ResourceProcessor#log] from inner class

### ISSUE THREAD

**Issue by amadfida** [mckenfra/gsp-resources#8]
GSP resources version : 0.4.3
Resources Plugin version : 1.2.1

Error Fatal error during compilation org.apache.tools.ant.BuildException: BUG! exception in phase 'class generation' in source unit '/Users/amad/.grails/2.2.4/projects/brinqa/plugins/gsp-resources-0.4.3/src/groovy/org/grails/plugin/gspresources/GspResourceProcessor.groovy' Trying to access private constant field [org.grails.plugin.resource.ResourceProcessor#log] from inner class (Use --stacktrace to see the full trace)

**Comment by amadfida** [comment]
Rolling back to 0.4.1 fixes this.

**Comment by mckenfra** [comment]
Hi,

Thanks very much for raising this. Looks like a change in the `resources` plugin in version `1.2.1` is causing the issue. I have released version `0.4.4-SNAPSHOT` of `gsp-resources`, can you see if it fixes your problem?

You will need to add the following to your `BuildConfig.groovy`:

```
runtime ':gsp-resources:0.4.4-SNAPSHOT'
```

**Comment by amadfida** [comment]
Will do and let you know right away.

On Thursday, September 26, 2013, mckenfra wrote:

> Hi,
> 
> Thanks very much for raising this. Looks like a change in the resourcesplugin in version
> 1.2.1 is causing the issue. I have released version 0.4.4-SNAPSHOT of
> gsp-resources, can you see if it fixes your problem?
> 
> You will need to add the following to your BuildConfig.groovy:
> 
> runtime ':gsp-resources:0.4.4-SNAPSHOT'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mckenfra/gsp-resources/issues/8#issuecomment-25155790
> .

## 

 -a

**Comment by mckenfra** [comment]
Hi,
Did you manage to test it? If it's working ok, I'll roll it out it as the latest integration version.
Cheers,
Francis

**Comment by amadfida** [comment]
Give me few hours and I will confirm -- sorry for the delay.

On Friday, September 27, 2013, mckenfra wrote:

> Hi,
> Did you manage to test it? If it's working ok, I'll roll it out it as the
> latest integration version.
> Cheers,
> Francis
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mckenfra/gsp-resources/issues/8#issuecomment-25289448
> .

## 

 -a

**Comment by amadfida** [comment]
Looks good - lets release it.

Amad

 -a

**Comment by mckenfra** [comment]
Fixed in version 0.4.4
